import './navbar.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet" />
      </head>
      <body style={{ fontFamily: 'Roboto, Arial, sans-serif' }}>
        <div className="topnav">
          <a href="#blog">Blog</a>
          <a href="#videos">Videos</a>
          <a href="#about">About</a>
        </div>
        {children}
      </body>
    </html>
  )
}
